services:
    Plenta\ContaoJobsBasic\EventListener\Contao\DCA\TlPlentaJobsBasicOffer:
        public: true
        arguments:
            - '@Plenta\ContaoJobsBasic\Helper\EmploymentType'
            - '@Doctrine\Persistence\ManagerRegistry'
            - '@contao.slug'

    Plenta\ContaoJobsBasic\EventListener\Contao\DCA\TlPlentaJobsBasicJobLocation:
        public: true

    Plenta\ContaoJobsBasic\EventListener\Contao\DCA\TlPlentaJobsBasicSettingsEmploymentType:
        public: true
        arguments:
            - '@Plenta\ContaoJobsBasic\Helper\DataTypeMapper'
            - '@Plenta\ContaoJobsBasic\Helper\EmploymentType'

    # Contao Hooks
    Plenta\ContaoJobsBasic\EventListener\Contao\DCA\SetPtableForContentListener:
        tags:
            - { name: contao.hook, hook: loadDataContainer, method: setPtableForContentListener, priority: 0 }
        arguments:
            - '@request_stack'
            - '@contao.routing.scope_matcher'

    Plenta\ContaoJobsBasic\EventListener\Contao\BackendMenuListener:
        public: true
        tags:
            - { name: kernel.event_listener, event: contao.backend_menu_build, priority: -255 }
        arguments:
          - '@router'
          - '@request_stack'

    Plenta\ContaoJobsBasic\EventListener\Contao\DCA\TlModule:
        public: true
        arguments: ['@Doctrine\Persistence\ManagerRegistry']