plenta_jobs_basic.offer_filter:
    path: /_plenta-jobs-basic/offer/filter
    defaults:
        _scope: frontend
        _token_check: false
        _controller: "PlentaContaoJobsBasicBundle:JobsOfferFilterRequest:filterOffers"

Plenta\ContaoJobsBasic\Controller\Contao\BackendModule\SettingsController:
    path: /contao/plentajobsbasic/settings
    defaults:
        _scope: backend
        _controller: Plenta\ContaoJobsBasic\Controller\Contao\BackendModule\SettingsController::showSettings