services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Plenta\ContaoJobsBasic\:
        resource: ../../../../../src/Plenta/ContaoJobsBasic/*
        exclude: ../../../../../src/Plenta/ContaoJobsBasic/{Entity,Migrations,Resources,Tests}

    Plenta\ContaoJobsBasic\Helper\EmploymentType:
        class: Plenta\ContaoJobsBasic\Helper\EmploymentType
        arguments:
            - '@translator'
            - '@Doctrine\Persistence\ManagerRegistry'
            - '@request_stack'

    Plenta\ContaoJobsBasic\Helper\DataTypeMapper:
        class: Plenta\ContaoJobsBasic\Helper\DataTypeMapper
        arguments:
            - '@contao.framework'

    Plenta\ContaoJobsBasic\GoogleForJobs\GoogleForJobs:
        class: Plenta\ContaoJobsBasic\GoogleForJobs\GoogleForJobs
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
            - '@contao.image.picture_factory'
            - '@contao.assets.files_context'
            - '@Plenta\ContaoJobsBasic\Helper\EmploymentType'
            - '%kernel.project_dir%'

    # Migrations
    Plenta\ContaoJobsBasic\Migration\RenameDatabaseColumnsMigration:
        public: true
        tags:
            - { name: contao.migration, priority: 0 }
